### ISSUE TITLE
Stats bar should update periodically

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#116]
CPU and RAM usage are prone to changing frequently, so if the stats bar never updates after loading the page then it won't really be of much use.

Update the axios call such that it re-runs every so often. Some details are likely to change more than others (CPU changing constantly vs disk once in a blue moon) but for now it's probably enough to just ping every 30 seconds or minute.

**Comment by stoppert** [comment]
Working on this issue now.
