### ISSUE TITLE
Use CodeMirror for syntax highlighting

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#135]
While the file viewer works, a plain `<pre>` element is a bit... plain. There are easier options for highlighting alone but at some point we'll also need to edit, so we might as well add [CodeMirror](https://codemirror.net) in the first place to save replacing it later.

It also has the benefit of supporting different colour schemes and editing modes (Vim, emacs and sublime) which would be useful to implement eventually. Until the API supports editing files though, we can keep it read-only.

**Comment by noreason** [comment]
Working on this issue now
