### ISSUE TITLE
Add psalm and phan

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#142]
PHPStan is great, but psalm and phan both hit on some things that the others miss. Problem is they seem to hit a lot of Laravel magic and don't know what to do with it, so they need some fine tuning to figure out how best to solve that first.

**todo:**
* [x] Add phan
* [x] Add psalm

**Comment by flow-control** [comment]
Hey @dshoreman,

i added `vimeo/psalm` to the tool, including the test pipeline in #166, hope you like it, the test pipeline is green :smile: 

Regards
/Flo
