### ISSUE TITLE
Remove version information from the Login page

### ISSUE THREAD

**Issue by noreason** [dshoreman/servidor#149]
The version information, ie "Servidor v0.4.0" located at the bottom of the login page could/should be removed

**Comment by andrelmlins** [comment]
I would like to help

**Comment by noreason** [comment]
ah sorry i should have mentioned that i was working on it

**Comment by dshoreman** [comment]
@noreason Thanks! Assigned you to the issue. Not really sure why the version info is showing on the login page (it shouldn't be using the main layout) but this definitely needs fixing.

@andrelmlins Feel free to check the other open issues, there are [a few I've tagged up](https://github.com/dshoreman/servidor/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Ahacktoberfest) with the `hacktoberfest` label which could be fairly quick to solve.

**Comment by andrelmlins** [comment]
rsrs, I ended up sending an attempt to correct, look at others
