### ISSUE TITLE
Can't open users in editor after update

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#154]
Once you update a user, if you try to open that user back in the editor, it fails and displays a blank form. It seems to be an issue with updating the user's groups as it only affects the user being saved.

### Replication Steps
1. Click any user (e.g. `ubuntu`) in System/Users to open the editor
2. Add a new group from the list
3. Click Update
4. Try to open that same user without reloading the page

### Expectation
The user is updated, and loaded back up with its new details in the editor

### Reality
An error is thrown in the console, and instead of seeing the editor populated with the user details, you get an empty Create form.

**Error details:**
```
[Vue warn]: Error in render: "TypeError: _vm.tmpUser.groups is undefined"

found in

---> <SystemUserEditor> at resources/js/components/System/UserEditor.vue
       <SuiGridColumn>
         <SuiGrid>
           <SystemUsers> at resources/js/components/System/Users.vue
             <Servidor> at resources/js/layouts/Servidor.vue
               <Root>
```

**Comment by RageZBla** [comment]
@dshoreman let me see if I can fix it :thinking:
