### ISSUE TITLE
Group's users aren't updated in the list

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#155]
If you add a user to a group, that new user is reflected in the Groups list on the left.

If however you *remove* a user from that group, the removed user is still visible in the list even though when you click to edit the group again, the editor shows the correct users.

The screenshot below shows the state after removing the "vagrant" user from "adm", saving and re-opening the editor. There seems to be a clash between the `props` and `data` in the `system-group-item` component, so it could just be a case of replacing data with computed (or removing the aliases).

![image](https://user-images.githubusercontent.com/1521802/66102793-7a90f780-e5ab-11e9-990e-16e624bc2f2b.png)

**Comment by RageZBla** [comment]
@dshoreman I'll give it a shot and see if I can figure it out
