### ISSUE TITLE
Show true system hostname in app layout

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#21]
Instead of displaying the machine name, the StatsBar component is currently displaying 'host' information from the HTTP request. In many cases, this will simply be `localhost`, which is less than useful.

Replace `request()->getHost()` (added in #10) with something equivalent to the output of `hostname` or `cat /etc/hostname` on Linux/OSX.

The best solution would be a new `GET /api/system/status` API (with tests) which returns a simple key-value array. This could then be fetched to update *all* information in the StatsBar component, rather than only the hostname.

**Comment by nidble** [comment]
Hi @dshoreman,

shall I like to work on this...

**Comment by dshoreman** [comment]
@nidble Go ahead, I'll be busy working on #19 so I can't get to this for a bit.

You can use `exec('hostname')` to get the system hostname. You'd need to add a new `StatusController` in the System namespace, then use axios in the `StatsBar` component to fetch `/api/system/status` and update the page accordingly.

**Comment by nidble** [comment]
Ok, @dshoreman no problem.

But IMHO this task can be also accomplished directly with `gethostname()` (http://php.net/manual/en/function.gethostname.php).

Let me know if you prefer this solution and if you want to implement it in async manner rather than directly with php without axios and js.

**Comment by dshoreman** [comment]
`gethostname()` is even better @nidble, thanks for the suggestion.

I'd still like to go the async route if possible, as that allows for easier expansion in the future. While I haven't decided exactly what to include yet, I expect `/api/system/status` to eventually respond something like this:
```
{
  "cpu": {
    "user": 1.5,
    "system": 6.3,
    "idle": 92.2
  },
  "hostname": "jills-laptop",
  "mem": {
    "used": 1842,
    "free": 206,
    "total": 2048
  }
}
```

Of course, just the hostname field is good for now 😉
