### ISSUE TITLE
FontAwesome icons are not loading

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#5]
Instead of the icons defined in code, all are loading as the 'invalid' placeholder.

Project is using SemanticUI for CSS, with scripts from [Semantic-UI-Vue](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue) (installed via npm) which is probably why it lacks FA.

May just need to add the FA script either to `package.json`, or `layouts/app` via CDN.

![image](https://user-images.githubusercontent.com/1521802/46598106-bb5e4980-cada-11e8-8d76-8aa4305a3b40.png)

**Comment by nidble** [comment]
Can I work on this?

**Comment by dshoreman** [comment]
Sure! PRs can be based on/submitted to develop
