### ISSUE TITLE
Switch placeholder out for real system hostname

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/servidor#6]
In the `StatsBar` Vue component, 'Carbon' should be replaced with the hostname of the, well, host.

If FQDN is availble, short version is preferred. FQDN could optionally be displayed [in a popup](https://semantic-ui.com/modules/popup.html).

For now, it would suffice to pass values directly to the Vue component from Laravel in the `layouts.app` Blade template.

**Comment by nidble** [comment]
Can I work on this? :-)

**Comment by dshoreman** [comment]
Replying a tad late, I just got back from work.

No need to ask, you can work on as many or as few as you like ;)

**Comment by nidble** [comment]
@dshoreman no problem! I supposed you were at work. 

I pushed a PR, hope it is useful :-)

**Comment by dshoreman** [comment]
Thanks! Looks good so I've merged it, but I'll have to wait until later to try it out.

**Comment by dshoreman** [comment]
Forgot this one was still here. Closing in favour of #21.
